spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/re100
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: none
